/// @param hitbox
// returns the total number of frames a hitbox has been displayed

var result = 0;

// trick for calling outside of hitboxes
if (argument_count > 0) {
	with (argument[0]) {
		result = hitbox_frames_displayed();
	}
	return result;
}

if (permenant) return 0; // useful for comparisons we may need

/*
This number is generated by starting with the frame_count, which is the
number of frames the current subimage has been displayed. We then iterate
over the remaining sub images (everything below the current), and adding 
up the number of frames in the hitbox_frames list for each subimage.
*/

var result = frame_count;

for (var i = 0; i < image_index; i++) {
	result += ds_list_find_value(hitbox_frames, i);
}

return result;